/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "fullscreen.c"
#include "inplacerotate.c"
#include "pertag.c"
#include "scratchpad.c"
#include "selfrestart.c"
#include "shift.c"
#include "shiftboth.c"
#include "shiftswaptags.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swallow.c"
#include "swaptags.c"
#include "tapresize.c"
#include "vanitygaps.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_flextile-deluxe.c"
#include "layout_gapplessgrid.c"
#include "layout_grid.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_nrowgrid.c"
#include "layout_tile.c"

// Self Added
#include "shiftbothclients.c"
#include "resetlayout.c"
#include "bulkill.c"

