/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "fullscreen.h"
#include "inplacerotate.h"
#include "pertag.h"
#include "scratchpad.h"
#include "selfrestart.h"
#include "shift.h"
#include "shiftboth.h"
#include "shiftswaptags.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#include "sticky.h"
#include "swallow.h"
#include "swaptags.h"
#include "tapresize.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_flextile-deluxe.h"
#include "layout_gapplessgrid.h"
#include "layout_grid.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_nrowgrid.h"
#include "layout_tile.h"

// Self Added
#include "shiftbothclients.h"
#include "resetlayout.h"
#include "bulkill.h"

